# -*- coding: utf-8 -*-
from envparse import env

CIRCLE_TOKEN = env.str("CIRCLE_TOKEN")
GECKOBOARD_API_KEY = env.str("GECKOBOARD_API_KEY")
GECKOBOARD_PUSH_URL = env.str(
    "GECKOBOARD_PUSH_URL", default="https://push.geckoboard.com/v1/send/"
)
GECKOBOARD_CONTENT_DIFF_REPORTS_WIDGET_KEY = env.str(
    "GECKOBOARD_CONTENT_DIFF_REPORTS_WIDGET_KEY"
)
GECKOBOARD_DIRECTORY_TESTS_RESULTS_WIDGET_KEY = env.str(
    "GECKOBOARD_DIRECTORY_TESTS_RESULTS_WIDGET_KEY"
)
GECKOBOARD_LINKS_TO_USEFUL_CONTENT_TEST_JOBS_WIDGET_KEY = env.str(
    "GECKOBOARD_LINKS_TO_USEFUL_CONTENT_TEST_JOBS_WIDGET_KEY"
)
GECKOBOARD_PERIODIC_TESTS_RESULTS_WIDGET_KEY = env.str(
    "GECKOBOARD_PERIODIC_TESTS_RESULTS_WIDGET_KEY"
)
GECKOBOARD_TEST_RESULTS_WIDGET_KEY = env.str("GECKOBOARD_TEST_RESULTS_WIDGET_KEY")
GECKOBOARD_TOOLS_JIRA_QUERY_LINKS_WIDGET_KEY = env.str(
    "GECKOBOARD_TOOLS_JIRA_QUERY_LINKS_WIDGET_KEY"
)
JIRA_HOST = env.str("JIRA_HOST")
JIRA_TOKEN = env.str("JIRA_TOKEN")
JIRA_USERNAME = env.str("JIRA_USERNAME")
PA11Y_PASSWORD = env.str("PA11Y_PASSWORD")
PA11Y_URL = env.str("PA11Y_URL")
PA11Y_USERNAME = env.str("PA11Y_USERNAME")
