FROM python:3.5

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements_functional.txt /usr/src/app/
# Different src directory for pip to prevent 'pip install -e' packages to be installed in /usr/src/app/
RUN pip install --no-cache-dir -r requirements_functional.txt --src /usr/local/src

# install heroku app
RUN wget -q https://cli-assets.heroku.com/heroku-cli/channels/stable/heroku-cli-linux-x64.tar.gz -O heroku.tar.gz && \
	tar -xzf heroku.tar.gz && \
	mkdir -p /usr/local/lib /usr/local/bin && \
	mv heroku-cli-v6.*-linux-64 /usr/local/lib/heroku && \
	ln -s /usr/local/lib/heroku/bin/heroku /usr/local/bin/heroku

# Install dockerize https://github.com/jwilder/dockerize
ENV DOCKERIZE_VERSION v0.2.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

CMD ["/usr/src/app/docker/cmd-run.sh"]

COPY . /usr/src/app

