FROM python:3.6.6

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements_browser.txt /usr/src/app/requirements.txt
RUN pip install --upgrade pip
# Different src directory for pip to prevent 'pip install -e' packages to be installed in /usr/src/app/
RUN pip install -q --no-cache-dir -r requirements.txt --src /usr/local/src

CMD ["/usr/src/app/docker/cmd-run.sh"]

COPY . /usr/src/app
