# -*- coding: utf-8 -*-
__all__ = [
    "about_us",
    "about_the_uk",
    "buy_from_the_uk",
    "industries",
    "industry",
    "landing",
    "international_contact_us",
    "international_contact_us_capital_invest",
    "international_contact_us_capital_invest_thank_you",
    "international_contact_us_exporting_to_the_uk",
    "international_contact_us_thank_you",
    "international_transition_period_enquiries_contact_us",
    "international_transition_period_enquiries_contact_us_thank_you",
    "news_international",
    "news_international_article",
    "region",
    "regions_landing",
    "trade_contact_us",
    "trade_contact_us_thank_you",
]
