Feature: Find content differences between Staging and UAT International environments

  Scenario Outline: Content on Staging page "<selected>" should be the same as on respective UAT page
    When you look at the "main" section of the "<selected>" page on "International" "STAGE" and "UAT"

    Then there should be no differences

    Examples: All known pages
      | selected                                                                                                   |
      | /                                                                                                          |
      | ?lang=de                                                                                                   |
      | ?lang=en-gb                                                                                                |
      | ?lang=es                                                                                                   |
      | ?lang=fr                                                                                                   |
      | ?lang=ja                                                                                                   |
      | ?lang=pt                                                                                                   |
      | ?lang=zh-hans                                                                                              |
      | about-uk/why-choose-uk/business-environment-guide/                                                         |
      | contact/                                                                                                   |
      | content/about-dit/                                                                                         |
      | content/about-dit/how-we-help-you-buy-uk/                                                                  |
      | content/about-uk/                                                                                          |
      | content/about-uk/?lang=de                                                                                  |
      | content/about-uk/?lang=es                                                                                  |
      | content/about-uk/?lang=fr                                                                                  |
      | content/about-uk/?lang=ja                                                                                  |
      | content/about-uk/?lang=pt                                                                                  |
      | content/about-uk/?lang=zh-hans                                                                             |
      | content/about-uk/industries/                                                                               |
      | content/about-uk/industries/?lang=de                                                                       |
      | content/about-uk/industries/?lang=es                                                                       |
      | content/about-uk/industries/?lang=fr                                                                       |
      | content/about-uk/industries/?lang=ja                                                                       |
      | content/about-uk/industries/?lang=pt                                                                       |
      | content/about-uk/industries/?lang=zh-hans                                                                  |
      | content/about-uk/industries/aerospace/                                                                     |
      | content/about-uk/industries/aerospace/?lang=de                                                             |
      | content/about-uk/industries/aerospace/?lang=es                                                             |
      | content/about-uk/industries/aerospace/?lang=fr                                                             |
      | content/about-uk/industries/aerospace/?lang=pt                                                             |
      | content/about-uk/industries/aerospace/?lang=zh-hans                                                        |
      | content/about-uk/industries/agricultural-technology/                                                       |
      | content/about-uk/industries/agricultural-technology/uk-agritech-strengths/                                 |
      | content/about-uk/industries/airports/                                                                      |
      | content/about-uk/industries/automotive/                                                                    |
      | content/about-uk/industries/automotive/?lang=de                                                            |
      | content/about-uk/industries/automotive/?lang=es                                                            |
      | content/about-uk/industries/automotive/?lang=fr                                                            |
      | content/about-uk/industries/automotive/?lang=ja                                                            |
      | content/about-uk/industries/automotive/?lang=pt                                                            |
      | content/about-uk/industries/automotive/?lang=zh-hans                                                       |
      | content/about-uk/industries/construction/                                                                  |
      | content/about-uk/industries/creative-industries/                                                           |
      | content/about-uk/industries/creative-industries/?lang=de                                                   |
      | content/about-uk/industries/creative-industries/?lang=es                                                   |
      | content/about-uk/industries/creative-industries/?lang=fr                                                   |
      | content/about-uk/industries/creative-industries/?lang=ja                                                   |
      | content/about-uk/industries/creative-industries/?lang=pt                                                   |
      | content/about-uk/industries/creative-industries/?lang=zh-hans                                              |
      | content/about-uk/industries/cyber-security/                                                                |
      | content/about-uk/industries/education/                                                                     |
      | content/about-uk/industries/energy/                                                                        |
      | content/about-uk/industries/engineering-and-manufacturing/                                                 |
      | content/about-uk/industries/engineering-and-manufacturing/?lang=de                                         |
      | content/about-uk/industries/engineering-and-manufacturing/?lang=es                                         |
      | content/about-uk/industries/engineering-and-manufacturing/?lang=fr                                         |
      | content/about-uk/industries/engineering-and-manufacturing/?lang=ja                                         |
      | content/about-uk/industries/engineering-and-manufacturing/?lang=pt                                         |
      | content/about-uk/industries/engineering-and-manufacturing/?lang=zh-hans                                    |
      | content/about-uk/industries/financial-and-professional-services/                                           |
      | content/about-uk/industries/financial-and-professional-services/?lang=de                                   |
      | content/about-uk/industries/financial-services/                                                            |
      | content/about-uk/industries/financial-services/?lang=de                                                    |
      | content/about-uk/industries/financial-services/?lang=es                                                    |
      | content/about-uk/industries/financial-services/?lang=fr                                                    |
      | content/about-uk/industries/financial-services/?lang=pt                                                    |
      | content/about-uk/industries/financial-services/?lang=zh-hans                                               |
      | content/about-uk/industries/financial-services/building-fintech-bridges/                                   |
      | content/about-uk/industries/financial-services/building-fintech-bridges/?lang=de                           |
      | content/about-uk/industries/food-and-drink/                                                                |
      | content/about-uk/industries/health-and-life-sciences/                                                      |
      | content/about-uk/industries/health-and-life-sciences/?lang=de                                              |
      | content/about-uk/industries/health-and-life-sciences/?lang=es                                              |
      | content/about-uk/industries/health-and-life-sciences/?lang=fr                                              |
      | content/about-uk/industries/health-and-life-sciences/?lang=pt                                              |
      | content/about-uk/industries/health-and-life-sciences/?lang=zh-hans                                         |
      | content/about-uk/industries/legal-services/                                                                |
      | content/about-uk/industries/maritime/                                                                      |
      | content/about-uk/industries/mining/                                                                        |
      | content/about-uk/industries/nuclear-energy/                                                                |
      | content/about-uk/industries/oil-and-gas/                                                                   |
      | content/about-uk/industries/rail/                                                                          |
      | content/about-uk/industries/real-estate/                                                                   |
      | content/about-uk/industries/retail/                                                                        |
      | content/about-uk/industries/space/                                                                         |
      | content/about-uk/industries/space/?lang=de                                                                 |
      | content/about-uk/industries/space/?lang=es                                                                 |
      | content/about-uk/industries/space/?lang=fr                                                                 |
      | content/about-uk/industries/space/?lang=ja                                                                 |
      | content/about-uk/industries/space/?lang=pt                                                                 |
      | content/about-uk/industries/space/?lang=zh-hans                                                            |
      | content/about-uk/industries/sports-economy/                                                                |
      | content/about-uk/industries/technology/                                                                    |
      | content/about-uk/industries/technology/?lang=de                                                            |
      | content/about-uk/industries/technology/?lang=es                                                            |
      | content/about-uk/industries/technology/?lang=fr                                                            |
      | content/about-uk/industries/technology/?lang=pt                                                            |
      | content/about-uk/industries/technology/?lang=zh-hans                                                       |
      | content/about-uk/industries/technology/uk-ces-2019/                                                        |
      | content/about-uk/industries/water/                                                                         |
      | content/about-uk/regions/                                                                                  |
      | content/about-uk/regions/midlands/                                                                         |
      | content/about-uk/regions/north-england/                                                                    |
      | content/about-uk/regions/northern-ireland/                                                                 |
      | content/about-uk/regions/scotland/                                                                         |
      | content/about-uk/regions/south-england/                                                                    |
      | content/about-uk/regions/wales/                                                                            |
      | content/about-uk/why-choose-uk/                                                                            |
      | content/about-uk/why-choose-uk/?lang=de                                                                    |
      | content/about-uk/why-choose-uk/?lang=es                                                                    |
      | content/about-uk/why-choose-uk/?lang=fr                                                                    |
      | content/about-uk/why-choose-uk/?lang=ja                                                                    |
      | content/about-uk/why-choose-uk/?lang=pt                                                                    |
      | content/about-uk/why-choose-uk/?lang=zh-hans                                                               |
      | content/about-uk/why-choose-uk/access-finance-in-the-uk/                                                   |
      | content/about-uk/why-choose-uk/hire-skilled-workers-for-your-uk-operations/                                |
      | content/about-uk/why-choose-uk/tax-incentives/                                                             |
      | content/about-uk/why-choose-uk/tax-incentives/?lang=de                                                     |
      | content/about-uk/why-choose-uk/tax-incentives/?lang=es                                                     |
      | content/about-uk/why-choose-uk/tax-incentives/?lang=fr                                                     |
      | content/about-uk/why-choose-uk/tax-incentives/?lang=ja                                                     |
      | content/about-uk/why-choose-uk/tax-incentives/?lang=pt                                                     |
      | content/about-uk/why-choose-uk/tax-incentives/?lang=zh-hans                                                |
      | content/about-uk/why-choose-uk/uk-corporation-tax/                                                         |
      | content/about-uk/why-choose-uk/uk-infrastructure/                                                          |
      | content/about-uk/why-choose-uk/uk-infrastructure/?lang=de                                                  |
      | content/about-uk/why-choose-uk/uk-infrastructure/?lang=es                                                  |
      | content/about-uk/why-choose-uk/uk-infrastructure/?lang=fr                                                  |
      | content/about-uk/why-choose-uk/uk-infrastructure/?lang=ja                                                  |
      | content/about-uk/why-choose-uk/uk-infrastructure/?lang=pt                                                  |
      | content/about-uk/why-choose-uk/uk-infrastructure/?lang=zh-hans                                             |
      | content/about-uk/why-choose-uk/uk-innovation/                                                              |
      | content/about-uk/why-choose-uk/uk-innovation/?lang=de                                                      |
      | content/about-uk/why-choose-uk/uk-innovation/?lang=es                                                      |
      | content/about-uk/why-choose-uk/uk-innovation/?lang=fr                                                      |
      | content/about-uk/why-choose-uk/uk-innovation/?lang=ja                                                      |
      | content/about-uk/why-choose-uk/uk-innovation/?lang=pt                                                      |
      | content/about-uk/why-choose-uk/uk-innovation/?lang=zh-hans                                                 |
      | content/about-uk/why-choose-uk/uk-talent-and-labour/                                                       |
      | content/about-uk/why-choose-uk/uk-talent-and-labour/?lang=de                                               |
      | content/about-uk/why-choose-uk/uk-talent-and-labour/?lang=es                                               |
      | content/about-uk/why-choose-uk/uk-talent-and-labour/?lang=fr                                               |
      | content/about-uk/why-choose-uk/uk-talent-and-labour/?lang=ja                                               |
      | content/about-uk/why-choose-uk/uk-talent-and-labour/?lang=pt                                               |
      | content/about-uk/why-choose-uk/uk-talent-and-labour/?lang=zh-hans                                          |
      | content/about-uk/why-choose-uk/uk-tax-and-incentives/                                                      |
      | content/about-us/                                                                                          |
      | content/about-us/?lang=de                                                                                  |
      | content/about-us/?lang=es                                                                                  |
      | content/about-us/?lang=fr                                                                                  |
      | content/about-us/?lang=ja                                                                                  |
      | content/about-us/?lang=pt                                                                                  |
      | content/about-us/?lang=zh-hans                                                                             |
      | content/campaigns/                                                                                         |
      | content/campaigns/life-changing-artificial-intelligence-ai/                                                |
      | content/capital-invest/                                                                                    |
      | content/capital-invest/?lang=de                                                                            |
      | content/capital-invest/?lang=es                                                                            |
      | content/capital-invest/?lang=fr                                                                            |
      | content/capital-invest/?lang=ja                                                                            |
      | content/capital-invest/?lang=pt                                                                            |
      | content/capital-invest/?lang=zh-hans                                                                       |
      | content/capital-invest/contact/                                                                            |
      | content/capital-invest/contact/?lang=de                                                                    |
      | content/capital-invest/contact/?lang=es                                                                    |
      | content/capital-invest/contact/?lang=fr                                                                    |
      | content/capital-invest/contact/?lang=ja                                                                    |
      | content/capital-invest/contact/?lang=pt                                                                    |
      | content/capital-invest/contact/?lang=zh-hans                                                               |
      | content/capital-invest/how-we-help-you-invest-capital-uk/                                                  |
      | content/capital-invest/how-we-help-you-invest-capital-uk/international/content/capital-invest/contact/     |
      | content/capital-invest/how-we-help-you-invest-capital/                                                     |
      | content/capital-invest/how-we-help-you-invest-capital/?lang=de                                             |
      | content/capital-invest/how-we-help-you-invest-capital/?lang=es                                             |
      | content/capital-invest/how-we-help-you-invest-capital/?lang=fr                                             |
      | content/capital-invest/how-we-help-you-invest-capital/?lang=ja                                             |
      | content/capital-invest/how-we-help-you-invest-capital/?lang=pt                                             |
      | content/capital-invest/how-we-help-you-invest-capital/?lang=zh-hans                                        |
      | content/how-to-setup-in-the-uk/global-entrepreneur-program/                                                |
      | content/how-to-setup-in-the-uk/uk-visas-and-migration/                                                     |
      | content/invest/high-potential-opportunities/aquaculture/                                                   |
      | content/invest/high-potential-opportunities/contact/                                                       |
      | content/invest/high-potential-opportunities/food-production/                                               |
      | content/invest/high-potential-opportunities/high-productivity-food-production/                             |
      | content/invest/high-potential-opportunities/lightweight-structures/                                        |
      | content/invest/high-potential-opportunities/photonics-and-microelectronics/                                |
      | content/invest/high-potential-opportunities/rail-infrastructure/                                           |
      | content/invest/high-potential-opportunities/space/                                                         |
      | content/invest/high-potential-opportunities/sustainable-packaging/                                         |
      | content/invest/how-to-setup-in-the-uk/                                                                     |
      | content/invest/how-to-setup-in-the-uk/?lang=de                                                             |
      | content/invest/how-to-setup-in-the-uk/?lang=es                                                             |
      | content/invest/how-to-setup-in-the-uk/?lang=fr                                                             |
      | content/invest/how-to-setup-in-the-uk/?lang=pt                                                             |
      | content/invest/how-to-setup-in-the-uk/?lang=zh-hans                                                        |
      | content/invest/how-to-setup-in-the-uk/access-finance-in-the-uk/                                            |
      | content/invest/how-to-setup-in-the-uk/access-finance-in-the-uk/?lang=de                                    |
      | content/invest/how-to-setup-in-the-uk/access-finance-in-the-uk/?lang=es                                    |
      | content/invest/how-to-setup-in-the-uk/access-finance-in-the-uk/?lang=fr                                    |
      | content/invest/how-to-setup-in-the-uk/access-finance-in-the-uk/?lang=ja                                    |
      | content/invest/how-to-setup-in-the-uk/access-finance-in-the-uk/?lang=pt                                    |
      | content/invest/how-to-setup-in-the-uk/access-finance-in-the-uk/?lang=zh-hans                               |
      | content/invest/how-to-setup-in-the-uk/establish-a-base-for-business-in-the-uk/                             |
      | content/invest/how-to-setup-in-the-uk/ff                                                                   |
      | content/invest/how-to-setup-in-the-uk/flexible-uk-labour-terms/                                            |
      | content/invest/how-to-setup-in-the-uk/fr                                                                   |
      | content/invest/how-to-setup-in-the-uk/global-entrepreneur-program/                                         |
      | content/invest/how-to-setup-in-the-uk/global-entrepreneur-program/?lang=de                                 |
      | content/invest/how-to-setup-in-the-uk/global-entrepreneur-program/?lang=es                                 |
      | content/invest/how-to-setup-in-the-uk/global-entrepreneur-program/?lang=fr                                 |
      | content/invest/how-to-setup-in-the-uk/global-entrepreneur-program/?lang=ja                                 |
      | content/invest/how-to-setup-in-the-uk/global-entrepreneur-program/?lang=pt                                 |
      | content/invest/how-to-setup-in-the-uk/global-entrepreneur-program/?lang=zh-hans                            |
      | content/invest/how-to-setup-in-the-uk/hire-skilled-workers-for-your-uk-operations/                         |
      | content/invest/how-to-setup-in-the-uk/hire-skilled-workers-for-your-uk-operations/?lang=de                 |
      | content/invest/how-to-setup-in-the-uk/hire-skilled-workers-for-your-uk-operations/?lang=es                 |
      | content/invest/how-to-setup-in-the-uk/hire-skilled-workers-for-your-uk-operations/?lang=fr                 |
      | content/invest/how-to-setup-in-the-uk/hire-skilled-workers-for-your-uk-operations/?lang=ja                 |
      | content/invest/how-to-setup-in-the-uk/hire-skilled-workers-for-your-uk-operations/?lang=pt                 |
      | content/invest/how-to-setup-in-the-uk/hire-skilled-workers-for-your-uk-operations/?lang=zh-hans            |
      | content/invest/how-to-setup-in-the-uk/open-a-uk-business-bank-account/                                     |
      | content/invest/how-to-setup-in-the-uk/open-a-uk-business-bank-account/?lang=de                             |
      | content/invest/how-to-setup-in-the-uk/open-a-uk-business-bank-account/?lang=es                             |
      | content/invest/how-to-setup-in-the-uk/open-a-uk-business-bank-account/?lang=fr                             |
      | content/invest/how-to-setup-in-the-uk/open-a-uk-business-bank-account/?lang=ja                             |
      | content/invest/how-to-setup-in-the-uk/open-a-uk-business-bank-account/?lang=pt                             |
      | content/invest/how-to-setup-in-the-uk/open-a-uk-business-bank-account/?lang=zh-hans                        |
      | content/invest/how-to-setup-in-the-uk/register-a-company-in-the-uk/                                        |
      | content/invest/how-to-setup-in-the-uk/register-a-company-in-the-uk/?lang=de                                |
      | content/invest/how-to-setup-in-the-uk/register-a-company-in-the-uk/?lang=es                                |
      | content/invest/how-to-setup-in-the-uk/register-a-company-in-the-uk/?lang=fr                                |
      | content/invest/how-to-setup-in-the-uk/register-a-company-in-the-uk/?lang=ja                                |
      | content/invest/how-to-setup-in-the-uk/register-a-company-in-the-uk/?lang=pt                                |
      | content/invest/how-to-setup-in-the-uk/register-a-company-in-the-uk/?lang=zh-hans                           |
      | content/invest/how-to-setup-in-the-uk/research-and-development-rd-support-in-the-uk/                       |
      | content/invest/how-to-setup-in-the-uk/research-and-development-rd-support-in-the-uk/?lang=de               |
      | content/invest/how-to-setup-in-the-uk/research-and-development-rd-support-in-the-uk/?lang=es               |
      | content/invest/how-to-setup-in-the-uk/research-and-development-rd-support-in-the-uk/?lang=fr               |
      | content/invest/how-to-setup-in-the-uk/research-and-development-rd-support-in-the-uk/?lang=ja               |
      | content/invest/how-to-setup-in-the-uk/research-and-development-rd-support-in-the-uk/?lang=pt               |
      | content/invest/how-to-setup-in-the-uk/research-and-development-rd-support-in-the-uk/?lang=zh-hans          |
      | content/invest/how-to-setup-in-the-uk/transition-period/                                                   |
      | content/invest/how-to-setup-in-the-uk/transition-period/some cta link                                      |
      | content/invest/how-to-setup-in-the-uk/uk-capital-gains-tax/                                                |
      | content/invest/how-to-setup-in-the-uk/uk-corporation-tax/                                                  |
      | content/invest/how-to-setup-in-the-uk/uk-income-tax/                                                       |
      | content/invest/how-to-setup-in-the-uk/uk-infrastructure/                                                   |
      | content/invest/how-to-setup-in-the-uk/uk-labour-costs/                                                     |
      | content/invest/how-to-setup-in-the-uk/uk-labour-market/                                                    |
      | content/invest/how-to-setup-in-the-uk/uk-tax-and-incentives/                                               |
      | content/invest/how-to-setup-in-the-uk/uk-tax-and-incentives/?lang=de                                       |
      | content/invest/how-to-setup-in-the-uk/uk-tax-and-incentives/?lang=es                                       |
      | content/invest/how-to-setup-in-the-uk/uk-tax-and-incentives/?lang=fr                                       |
      | content/invest/how-to-setup-in-the-uk/uk-tax-and-incentives/?lang=ja                                       |
      | content/invest/how-to-setup-in-the-uk/uk-tax-and-incentives/?lang=pt                                       |
      | content/invest/how-to-setup-in-the-uk/uk-tax-and-incentives/?lang=zh-hans                                  |
      | content/invest/how-to-setup-in-the-uk/uk-venture-capital-schemes/                                          |
      | content/invest/how-we-help-you-expand-your-business-uk/                                                    |
      | content/invest/how-we-help-you-expand/                                                                     |
      | content/invest/how-we-help-you-expand/?lang=de                                                             |
      | content/invest/how-we-help-you-expand/?lang=es                                                             |
      | content/invest/how-we-help-you-expand/?lang=fr                                                             |
      | content/invest/how-we-help-you-expand/?lang=ja                                                             |
      | content/invest/how-we-help-you-expand/?lang=pt                                                             |
      | content/invest/how-we-help-you-expand/?lang=zh-hans                                                        |
      | content/invest/how-we-help-you-expand/international/invest/contact/                                        |
      | content/invest/uk-regions/midlands/                                                                        |
      | content/invest/uk-regions/midlands/?lang=de                                                                |
      | content/invest/uk-regions/midlands/?lang=es                                                                |
      | content/invest/uk-regions/midlands/?lang=fr                                                                |
      | content/invest/uk-regions/midlands/?lang=ja                                                                |
      | content/invest/uk-regions/midlands/?lang=pt                                                                |
      | content/invest/uk-regions/midlands/?lang=zh-hans                                                           |
      | content/invest/uk-regions/north-england/                                                                   |
      | content/invest/uk-regions/north-england/?lang=de                                                           |
      | content/invest/uk-regions/north-england/?lang=es                                                           |
      | content/invest/uk-regions/north-england/?lang=fr                                                           |
      | content/invest/uk-regions/north-england/?lang=ja                                                           |
      | content/invest/uk-regions/north-england/?lang=pt                                                           |
      | content/invest/uk-regions/north-england/?lang=zh-hans                                                      |
      | content/invest/uk-regions/northern-ireland/                                                                |
      | content/invest/uk-regions/northern-ireland/?lang=de                                                        |
      | content/invest/uk-regions/northern-ireland/?lang=es                                                        |
      | content/invest/uk-regions/northern-ireland/?lang=fr                                                        |
      | content/invest/uk-regions/northern-ireland/?lang=ja                                                        |
      | content/invest/uk-regions/northern-ireland/?lang=pt                                                        |
      | content/invest/uk-regions/northern-ireland/?lang=zh-hans                                                   |
      | content/invest/uk-regions/scotland/                                                                        |
      | content/invest/uk-regions/scotland/?lang=de                                                                |
      | content/invest/uk-regions/scotland/?lang=es                                                                |
      | content/invest/uk-regions/scotland/?lang=fr                                                                |
      | content/invest/uk-regions/scotland/?lang=ja                                                                |
      | content/invest/uk-regions/scotland/?lang=pt                                                                |
      | content/invest/uk-regions/scotland/?lang=zh-hans                                                           |
      | content/invest/uk-regions/south-england/                                                                   |
      | content/invest/uk-regions/south-england/?lang=de                                                           |
      | content/invest/uk-regions/south-england/?lang=es                                                           |
      | content/invest/uk-regions/south-england/?lang=fr                                                           |
      | content/invest/uk-regions/south-england/?lang=ja                                                           |
      | content/invest/uk-regions/south-england/?lang=pt                                                           |
      | content/invest/uk-regions/south-england/?lang=zh-hans                                                      |
      | content/invest/uk-regions/wales/                                                                           |
      | content/invest/uk-regions/wales/?lang=de                                                                   |
      | content/invest/uk-regions/wales/?lang=es                                                                   |
      | content/invest/uk-regions/wales/?lang=fr                                                                   |
      | content/invest/uk-regions/wales/?lang=ja                                                                   |
      | content/invest/uk-regions/wales/?lang=pt                                                                   |
      | content/invest/uk-regions/wales/?lang=zh-hans                                                              |
      | content/opportunities/aberdeen-hydrogen-infrastructure-development-programme/                              |
      | content/opportunities/advanced-manufacturing-innovation-district-scotland/                                 |
      | content/opportunities/belfast-waterside/                                                                   |
      | content/opportunities/birmingham-curzon/                                                                   |
      | content/opportunities/bristol-city-leap-programme/                                                         |
      | content/opportunities/cardiff-edge-life-sciences-park/                                                     |
      | content/opportunities/carlton-forest-energy-waste-facility/                                                |
      | content/opportunities/central-quay/                                                                        |
      | content/opportunities/cogen-energy-waste-facility-birmingham/                                              |
      | content/opportunities/cogen-energy-waste-facility/                                                         |
      | content/opportunities/energy-pivot-power-battery-storage-and-electric-vehicle-charging-portfolio/          |
      | content/opportunities/gridserve-electric-vehicle-forecourt-network/                                        |
      | content/opportunities/mcaleer-rushe-regeneration-projects-belfast-city-centre/                             |
      | content/opportunities/milford-waterfront/                                                                  |
      | content/opportunities/mira-technology-park-southern-manufacturing-sector/                                  |
      | content/opportunities/mishergas-waste-fuel-facility/                                                       |
      | content/opportunities/morlais-marine-energy-infrastructure-project/                                        |
      | content/opportunities/morlais-marine-energy/                                                               |
      | content/opportunities/nells-point-barry-island/                                                            |
      | content/opportunities/norwich-union-house-1-7-fountain-street-belfast/                                     |
      | content/opportunities/penrhos-coastal-holiday-resort/                                                      |
      | content/opportunities/real-estate-advanced-manufacturing-innovation-district-scotland/                     |
      | content/opportunities/real-estate-aero-centre-yorkshire/                                                   |
      | content/opportunities/real-estate-axiom-brand-playground/                                                  |
      | content/opportunities/real-estate-axiom-regional-shopping-centre/                                          |
      | content/opportunities/real-estate-bargate-quarter/                                                         |
      | content/opportunities/real-estate-belfast-waterside/                                                       |
      | content/opportunities/real-estate-bexhill-enterprise-park/                                                 |
      | content/opportunities/real-estate-bicester-motion/                                                         |
      | content/opportunities/real-estate-birmingham-curzon/                                                       |
      | content/opportunities/real-estate-bristol-temple-quarter/                                                  |
      | content/opportunities/real-estate-cambridge-innovation-parks/                                              |
      | content/opportunities/real-estate-camro/                                                                   |
      | content/opportunities/real-estate-canalside-and-interchange-project/                                       |
      | content/opportunities/real-estate-central-quay/                                                            |
      | content/opportunities/real-estate-corporation-street-and-tomb-street-belfast/                              |
      | content/opportunities/real-estate-cyber-central/                                                           |
      | content/opportunities/real-estate-dundee-waterfront/                                                       |
      | content/opportunities/real-estate-edinburgh-bioquarter/                                                    |
      | content/opportunities/real-estate-edinburgh-international-business-gateway/                                |
      | content/opportunities/real-estate-fawley-waterside/                                                        |
      | content/opportunities/real-estate-festival-gardens/                                                        |
      | content/opportunities/real-estate-festival-park/                                                           |
      | content/opportunities/real-estate-follingsby-max/                                                          |
      | content/opportunities/real-estate-forrest-park/                                                            |
      | content/opportunities/real-estate-friargate-coventry/                                                      |
      | content/opportunities/real-estate-future-carrington/                                                       |
      | content/opportunities/real-estate-future-park-fico/                                                        |
      | content/opportunities/real-estate-future-park/                                                             |
      | content/opportunities/real-estate-gateshead-quays/                                                         |
      | content/opportunities/real-estate-george-street-complex/                                                   |
      | content/opportunities/real-estate-gravity-smart-campus-somerset/                                           |
      | content/opportunities/real-estate-great-stall-east/                                                        |
      | content/opportunities/real-estate-great-stall-east/www.capitallandpropertygroup.co.uk                      |
      | content/opportunities/real-estate-heart-city-derby/                                                        |
      | content/opportunities/real-estate-island-site/                                                             |
      | content/opportunities/real-estate-jade-business-park/                                                      |
      | content/opportunities/real-estate-kimmerfields/                                                            |
      | content/opportunities/real-estate-kingmoor-park-enterprise-zone/                                           |
      | content/opportunities/real-estate-kirkstall-forge/                                                         |
      | content/opportunities/real-estate-liverpool-waters/                                                        |
      | content/opportunities/real-estate-magenta/                                                                 |
      | content/opportunities/real-estate-mcaleer-rushe-regeneration-projects-belfast-city-centre/                 |
      | content/opportunities/real-estate-mcaleer-rushe-regeneration-projects-belfast-city-centre/www.great.gov.uk |
      | content/opportunities/real-estate-mediacityuk/                                                             |
      | content/opportunities/real-estate-milford-waterfront/                                                      |
      | content/opportunities/real-estate-mira-technology-park-southern-manufacturing-sector/                      |
      | content/opportunities/real-estate-mku/                                                                     |
      | content/opportunities/real-estate-nells-point-barry-island/                                                |
      | content/opportunities/real-estate-north-essex-garden-communities/                                          |
      | content/opportunities/real-estate-norwich-union-house/                                                     |
      | content/opportunities/real-estate-otterpool-park/                                                          |
      | content/opportunities/real-estate-paddington-village/                                                      |
      | content/opportunities/real-estate-pall-mall-exchange/                                                      |
      | content/opportunities/real-estate-penrhos-coastal-holiday-resort/                                          |
      | content/opportunities/real-estate-perth-west/                                                              |
      | content/opportunities/real-estate-poole-town-centre-regeneration/                                          |
      | content/opportunities/real-estate-protos/                                                                  |
      | content/opportunities/real-estate-queen-street-clone/                                                      |
      | content/opportunities/real-estate-queen-street/                                                            |
      | content/opportunities/real-estate-sixth-building-royal-avenue-belfast/                                     |
      | content/opportunities/real-estate-sixth-royal-avenue-belfast/                                              |
      | content/opportunities/real-estate-stafford-gateway-north/                                                  |
      | content/opportunities/real-estate-stockport-exchange/                                                      |
      | content/opportunities/real-estate-swansea-central-phase-2/                                                 |
      | content/opportunities/real-estate-swansea-strategic-sites/                                                 |
      | content/opportunities/real-estate-swansea-strategic-sites/www.swansea.gov.uk/ldp                           |
      | content/opportunities/real-estate-titanic-quarter-belfast/                                                 |
      | content/opportunities/real-estate-trafford-waters/                                                         |
      | content/opportunities/real-estate-uk-central-hub-and-hs2-interchange/                                      |
      | content/opportunities/real-estate-unity/                                                                   |
      | content/opportunities/real-estate-waterside/                                                               |
      | content/opportunities/real-estate-weavers-cross/                                                           |
      | content/opportunities/real-estate-winter-gardens/                                                          |
      | content/opportunities/real-estate-wirral-waters/                                                           |
      | content/opportunities/real-estate-wisbech-garden-town/                                                     |
      | content/opportunities/real-estate-york-central/                                                            |
      | content/opportunities/reliagen-integrated-electric-vehicle-and-battery-storage-facility/                   |
      | content/opportunities/swansea-central-phase-2/                                                             |
      | content/opportunities/worcester-growth-corridor/                                                           |
      | content/topic/articles/                                                                                    |
      | content/topic/articles/this-is-an-article/                                                                 |
      | content/trade/how-we-help-you-buy/                                                                         |
      | content/trade/how-we-help-you-buy/?lang=de                                                                 |
      | content/trade/how-we-help-you-buy/?lang=es                                                                 |
      | content/trade/how-we-help-you-buy/?lang=fr                                                                 |
      | content/trade/how-we-help-you-buy/?lang=ja                                                                 |
      | content/trade/how-we-help-you-buy/?lang=pt                                                                 |
      | content/trade/how-we-help-you-buy/?lang=zh-hans                                                            |
      | invest/                                                                                                    |
      | invest/?lang=ar                                                                                            |
      | invest/?lang=de                                                                                            |
      | invest/?lang=es                                                                                            |
      | invest/?lang=fr                                                                                            |
      | invest/?lang=ja                                                                                            |
      | invest/?lang=pt                                                                                            |
      | invest/?lang=zh-hans                                                                                       |
      | invest/contact/                                                                                            |
      | invest/contact/?lang=de                                                                                    |
      | invest/contact/?lang=en-gb                                                                                 |
      | invest/contact/?lang=es                                                                                    |
      | invest/contact/?lang=fr                                                                                    |
      | invest/contact/?lang=ja                                                                                    |
      | invest/contact/?lang=pt                                                                                    |
      | invest/contact/?lang=zh-hans                                                                               |
      | investment-support-directory/                                                                              |
      | investment-support-directory/case-study/1503/sourcing-flexible-office-space-for-london-plc/                |
      | investment-support-directory/case-study/1505/growth-space-for-edtech-start-up-in-new-orleans-la/           |
      | investment-support-directory/case-study/1744/eos-uk/                                                       |
      | investment-support-directory/case-study/1795/danish-company-mobaro-select-jbprm-to-enter-uk-ene/           |
      | investment-support-directory/case-study/1855/digital-enablement-for-integrated-care-delivery-in/           |
      | investment-support-directory/case-study/1856/uk-market-entry-services/                                     |
      | investment-support-directory/case-study/1858/european-mhealth-guidelines/                                  |
      | investment-support-directory/case-study/1859/investment-cases-and-appraisals/                              |
      | investment-support-directory/case-study/1860/business-coaching/                                            |
      | investment-support-directory/case-study/1861/european-innovation-partnership-on-aha/                       |
      | investment-support-directory/case-study/1895/confetti-media-group/                                         |
      | investment-support-directory/case-study/1948/market-report-5-year-strategy-for-10-market-share/            |
      | investment-support-directory/case-study/2239/kolon-industries-s-korea-brand-owner-to-uk/                   |
      | investment-support-directory/case-study/2258/go-exporting-launches-new-fasttrack-service/                  |
      | investment-support-directory/case-study/2276/employment-compliance/                                        |
      | investment-support-directory/case-study/2277/establishing-a-uk-presence/                                   |
      | investment-support-directory/case-study/2280/cryogenesis-business-transformation-project/                  |
      | investment-support-directory/case-study/2286/fintech-startup/                                              |
      | investment-support-directory/case-study/2293/understanding-the-local-market-and-your-obligation/           |
      | investment-support-directory/case-study/2300/global-mobility-relocation-solutions/                         |
      | investment-support-directory/case-study/2313/advising-a-us-client-on-business-immigration-law/             |
      | investment-support-directory/case-study/2317/rushden-lakes-northamptonshire/                               |
      | investment-support-directory/case-study/2318/european-logistics/                                           |
      | investment-support-directory/case-study/2330/full-service-retail-pop-up-store/                             |
      | investment-support-directory/case-study/2366/saas-based-service-sales-success/                             |
      | investment-support-directory/case-study/2367/creating-a-worlwide-digital-presentation-agency/              |
      | investment-support-directory/case-study/2418/assisting-intentional-businesses-with-entry-to-the/           |
      | investment-support-directory/case-study/2423/agriwebb-invests-in-uk/                                       |
      | investment-support-directory/case-study/2434/accelerating-uk-sales-for-a-tech-sme/                         |
      | investment-support-directory/case-study/2440/inbound-trade-mission-of-13-technology-companies/             |
      | investment-support-directory/case-study/2459/bringing-a-leading-digital-design-studio-to-the-uk/           |
      | investment-support-directory/case-study/2462/sole-representative-of-an-overseas-business/                  |
      | investment-support-directory/case-study/2496/ring-of-security-limited-the-uk-subsidiary-of-ring/           |
      | investment-support-directory/case-study/2497/pharmamar/                                                    |
      | investment-support-directory/case-study/2498/strategic-partner-expansion-into-uk-market/                   |
      | investment-support-directory/case-study/2510/fca-authorisation-of-australian-fintech-company/              |
      | investment-support-directory/case-study/2585/talent-acquisition/                                           |
      | investment-support-directory/case-study/2594/uk-expansion-as-part-of-a-wider-internationalizati/           |
      | investment-support-directory/case-study/2615/acquiring-affordable-real-estate-in-mayfair-london/           |
      | investment-support-directory/case-study/2619/breaking-down-london-as-an-office-space-location/             |
      | investment-support-directory/case-study/2621/securing-private-office-space-for-a-charity-in-man/           |
      | investment-support-directory/case-study/2675/uk-employment-compliance-guide-plan-ahead/                    |
      | trade/                                                                                                     |
      | trade/?lang=de                                                                                             |
      | trade/?lang=es                                                                                             |
      | trade/?lang=fr                                                                                             |
      | trade/?lang=ja                                                                                             |
      | trade/?lang=pt                                                                                             |
      | trade/?lang=zh-hans                                                                                        |
      | trade/contact/                                                                                             |
      | trade/contact/?lang=ar                                                                                     |
      | trade/contact/?lang=de                                                                                     |
      | trade/contact/?lang=es                                                                                     |
      | trade/contact/?lang=fr                                                                                     |
      | trade/contact/?lang=ja                                                                                     |
      | trade/contact/?lang=pt                                                                                     |
      | trade/contact/?lang=zh-hans                                                                                |
      | trade/how-we-help-you-buy/why-buy-from-the-uk/                                                             |
