Feature: Find content differences between Production and UAT Invest environments

  Scenario Outline: Content on Dev page "<selected>" should be the same as on respective Production page
    When you look at the "main" section of the "<selected>" page on "Invest" "PROD" and "UAT"

    Then there should be no differences

    @wip
    Examples: missing translations
     | selected                                                                                              |
     | ar/industries/capital-investment/                                                                     |
     | ja/industries/capital-investment/                                                                     |
     | zh-hans/industries/capital-investment/                                                                |
     | ja/uk-regions/midlands/                                                                               |
     | de/uk-regions/midlands/                                                                               |
     | de/uk-setup-guide/establish-base-business-uk/                                                         |

    Examples: English
     | selected                                                                                              |
     | /                                                                                                     |
     | contact/                                                                                              |
     | industries/                                                                                           |
     | industries/advanced-manufacturing/                                                                    |
     | industries/aerospace/                                                                                 |
     | industries/agri-tech/                                                                                 |
     | industries/automotive/                                                                                |
     | industries/automotive/automotive-research-and-development/                                            |
     | industries/automotive/automotive-supply-chain/                                                        |
     | industries/automotive/motorsport/                                                                     |
     | industries/capital-investment/                                                                        |
     | industries/chemicals/                                                                                 |
     | industries/creative-industries/                                                                       |
     | industries/creative-industries/creative-content-and-production/                                       |
     | industries/creative-industries/digital-media/                                                         |
     | industries/energy/                                                                                    |
     | industries/energy/electrical-networks/                                                                |
     | industries/energy/energy-waste/                                                                       |
     | industries/energy/nuclear-energy/                                                                     |
     | industries/energy/offshore-wind-energy/                                                               |
     | industries/energy/oil-and-gas/                                                                        |
     | industries/financial-services/                                                                        |
     | industries/financial-services/asset-management/                                                       |
     | industries/financial-services/financial-technology/                                                   |
     | industries/food-and-drink/                                                                            |
     | industries/food-and-drink/food-service-and-catering/                                                  |
     | industries/food-and-drink/free-foods/                                                                 |
     | industries/food-and-drink/meat-poultry-and-dairy/                                                     |
     | industries/health-and-life-sciences/                                                                  |
     | industries/health-and-life-sciences/medical-technology/                                               |
     | industries/health-and-life-sciences/pharmaceutical-manufacturing/                                     |
     | industries/retail/                                                                                    |
     | industries/technology/                                                                                |
     | industries/technology/data-analytics/                                                                 |
     | uk-regions/london/                                                                                    |
     | uk-regions/midlands/                                                                                  |
     | uk-regions/north-england/                                                                             |
     | uk-regions/northern-ireland/                                                                          |
     | uk-regions/scotland/                                                                                  |
     | uk-regions/south-england/                                                                             |
     | uk-regions/wales/                                                                                     |
     | uk-setup-guide/                                                                                       |
     | uk-setup-guide/apply-uk-visa/                                                                         |
     | uk-setup-guide/establish-base-business-uk/                                                            |
     | uk-setup-guide/hire-skilled-workers-your-uk-operations/                                               |
     | uk-setup-guide/open-uk-business-bank-account/                                                         |
     | uk-setup-guide/setup-your-business-uk/                                                                |
     | uk-setup-guide/understand-uk-tax-and-incentives/                                                      |

    Examples: Arabic
     | selected                                                                                              |
     | ar/                                                                                                   |
     | ar/contact/                                                                                           |
     | ar/industries/                                                                                        |
     | ar/industries/advanced-manufacturing/                                                                 |
     | ar/industries/aerospace/                                                                              |
     | ar/industries/agri-tech/                                                                              |
     | ar/industries/automotive/                                                                             |
     | ar/industries/automotive/automotive-research-and-development/                                         |
     | ar/industries/automotive/automotive-supply-chain/                                                     |
     | ar/industries/automotive/motorsport/                                                                  |
     | ar/industries/chemicals/                                                                              |
     | ar/industries/creative-industries/                                                                    |
     | ar/industries/creative-industries/creative-content-and-production/                                    |
     | ar/industries/creative-industries/digital-media/                                                      |
     | ar/industries/energy/                                                                                 |
     | ar/industries/energy/electrical-networks/                                                             |
     | ar/industries/energy/energy-waste/                                                                    |
     | ar/industries/energy/nuclear-energy/                                                                  |
     | ar/industries/energy/offshore-wind-energy/                                                            |
     | ar/industries/energy/oil-and-gas/                                                                     |
     | ar/industries/financial-services/                                                                     |
     | ar/industries/financial-services/asset-management/                                                    |
     | ar/industries/financial-services/financial-technology/                                                |
     | ar/industries/food-and-drink/                                                                         |
     | ar/industries/food-and-drink/food-service-and-catering/                                               |
     | ar/industries/food-and-drink/free-foods/                                                              |
     | ar/industries/food-and-drink/meat-poultry-and-dairy/                                                  |
     | ar/industries/health-and-life-sciences/                                                               |
     | ar/industries/health-and-life-sciences/medical-technology/                                            |
     | ar/industries/health-and-life-sciences/pharmaceutical-manufacturing/                                  |
     | ar/industries/retail/                                                                                 |
     | ar/industries/technology/                                                                             |
     | ar/industries/technology/data-analytics/                                                              |
     | ar/uk-regions/london/                                                                                 |
     | ar/uk-regions/midlands/                                                                               |
     | ar/uk-regions/north-england/                                                                          |
     | ar/uk-regions/northern-ireland/                                                                       |
     | ar/uk-regions/scotland/                                                                               |
     | ar/uk-regions/south-england/                                                                          |
     | ar/uk-regions/wales/                                                                                  |
     | ar/uk-setup-guide/                                                                                    |
     | ar/uk-setup-guide/apply-uk-visa/                                                                      |
     | ar/uk-setup-guide/establish-base-business-uk/                                                         |
     | ar/uk-setup-guide/hire-skilled-workers-your-uk-operations/                                            |
     | ar/uk-setup-guide/open-uk-business-bank-account/                                                      |
     | ar/uk-setup-guide/setup-your-business-uk/                                                             |
     | ar/uk-setup-guide/understand-uk-tax-and-incentives/                                                   |

    Examples: German
     | selected                                                                                              |
     | de/                                                                                                   |
     | de/contact/                                                                                           |
     | de/industries/                                                                                        |
     | de/industries/advanced-manufacturing/                                                                 |
     | de/industries/aerospace/                                                                              |
     | de/industries/agri-tech/                                                                              |
     | de/industries/automotive/                                                                             |
     | de/industries/automotive/automotive-research-and-development/                                         |
     | de/industries/automotive/automotive-supply-chain/                                                     |
     | de/industries/automotive/motorsport/                                                                  |
     | de/industries/capital-investment/                                                                     |
     | de/industries/chemicals/                                                                              |
     | de/industries/creative-industries/                                                                    |
     | de/industries/creative-industries/creative-content-and-production/                                    |
     | de/industries/creative-industries/digital-media/                                                      |
     | de/industries/energy/                                                                                 |
     | de/industries/energy/electrical-networks/                                                             |
     | de/industries/energy/energy-waste/                                                                    |
     | de/industries/energy/nuclear-energy/                                                                  |
     | de/industries/energy/offshore-wind-energy/                                                            |
     | de/industries/energy/oil-and-gas/                                                                     |
     | de/industries/financial-services/                                                                     |
     | de/industries/financial-services/asset-management/                                                    |
     | de/industries/financial-services/financial-technology/                                                |
     | de/industries/health-and-life-sciences/                                                               |
     | de/industries/health-and-life-sciences/medical-technology/                                            |
     | de/industries/health-and-life-sciences/pharmaceutical-manufacturing/                                  |
     | de/industries/retail/                                                                                 |
     | de/industries/technology/                                                                             |
     | de/industries/technology/data-analytics/                                                              |
     | de/uk-regions/london/                                                                                 |
     | de/uk-regions/north-england/                                                                          |
     | de/uk-regions/northern-ireland/                                                                       |
     | de/uk-regions/scotland/                                                                               |
     | de/uk-regions/south-england/                                                                          |
     | de/uk-regions/wales/                                                                                  |
     | de/uk-setup-guide/                                                                                    |
     | de/uk-setup-guide/apply-uk-visa/                                                                      |
     | de/uk-setup-guide/hire-skilled-workers-your-uk-operations/                                            |
     | de/uk-setup-guide/open-uk-business-bank-account/                                                      |
     | de/uk-setup-guide/setup-your-business-uk/                                                             |
     | de/uk-setup-guide/understand-uk-tax-and-incentives/                                                   |

    Examples: Spanish
     | selected                                                                                              |
     | es/                                                                                                   |
     | es/contact/                                                                                           |
     | es/industries/                                                                                        |
     | es/industries/advanced-manufacturing/                                                                 |
     | es/industries/aerospace/                                                                              |
     | es/industries/agri-tech/                                                                              |
     | es/industries/automotive/                                                                             |
     | es/industries/automotive/automotive-research-and-development/                                         |
     | es/industries/automotive/automotive-supply-chain/                                                     |
     | es/industries/automotive/motorsport/                                                                  |
     | es/industries/capital-investment/                                                                     |
     | es/industries/chemicals/                                                                              |
     | es/industries/creative-industries/                                                                    |
     | es/industries/creative-industries/creative-content-and-production/                                    |
     | es/industries/creative-industries/digital-media/                                                      |
     | es/industries/energy/                                                                                 |
     | es/industries/energy/electrical-networks/                                                             |
     | es/industries/energy/energy-waste/                                                                    |
     | es/industries/energy/nuclear-energy/                                                                  |
     | es/industries/energy/offshore-wind-energy/                                                            |
     | es/industries/energy/oil-and-gas/                                                                     |
     | es/industries/financial-services/                                                                     |
     | es/industries/financial-services/asset-management/                                                    |
     | es/industries/financial-services/financial-technology/                                                |
     | es/industries/food-and-drink/                                                                         |
     | es/industries/food-and-drink/food-service-and-catering/                                               |
     | es/industries/food-and-drink/free-foods/                                                              |
     | es/industries/food-and-drink/meat-poultry-and-dairy/                                                  |
     | es/industries/health-and-life-sciences/                                                               |
     | es/industries/health-and-life-sciences/medical-technology/                                            |
     | es/industries/health-and-life-sciences/pharmaceutical-manufacturing/                                  |
     | es/industries/retail/                                                                                 |
     | es/industries/technology/                                                                             |
     | es/industries/technology/data-analytics/                                                              |
     | es/uk-regions/london/                                                                                 |
     | es/uk-regions/midlands/                                                                               |
     | es/uk-regions/north-england/                                                                          |
     | es/uk-regions/northern-ireland/                                                                       |
     | es/uk-regions/scotland/                                                                               |
     | es/uk-regions/south-england/                                                                          |
     | es/uk-regions/wales/                                                                                  |
     | es/uk-setup-guide/                                                                                    |
     | es/uk-setup-guide/apply-uk-visa/                                                                      |
     | es/uk-setup-guide/establish-base-business-uk/                                                         |
     | es/uk-setup-guide/hire-skilled-workers-your-uk-operations/                                            |
     | es/uk-setup-guide/open-uk-business-bank-account/                                                      |
     | es/uk-setup-guide/setup-your-business-uk/                                                             |
     | es/uk-setup-guide/understand-uk-tax-and-incentives/                                                   |

    Examples: French
     | selected                                                                                              |
     | fr/                                                                                                   |
     | fr/contact/                                                                                           |
     | fr/industries/                                                                                        |
     | fr/industries/advanced-manufacturing/                                                                 |
     | fr/industries/aerospace/                                                                              |
     | fr/industries/agri-tech/                                                                              |
     | fr/industries/automotive/                                                                             |
     | fr/industries/automotive/automotive-research-and-development/                                         |
     | fr/industries/automotive/automotive-supply-chain/                                                     |
     | fr/industries/automotive/motorsport/                                                                  |
     | fr/industries/capital-investment/                                                                     |
     | fr/industries/chemicals/                                                                              |
     | fr/industries/creative-industries/                                                                    |
     | fr/industries/creative-industries/creative-content-and-production/                                    |
     | fr/industries/creative-industries/digital-media/                                                      |
     | fr/industries/energy/                                                                                 |
     | fr/industries/energy/electrical-networks/                                                             |
     | fr/industries/energy/energy-waste/                                                                    |
     | fr/industries/energy/nuclear-energy/                                                                  |
     | fr/industries/energy/offshore-wind-energy/                                                            |
     | fr/industries/energy/oil-and-gas/                                                                     |
     | fr/industries/financial-services/                                                                     |
     | fr/industries/financial-services/asset-management/                                                    |
     | fr/industries/financial-services/financial-technology/                                                |
     | fr/industries/food-and-drink/                                                                         |
     | fr/industries/food-and-drink/food-service-and-catering/                                               |
     | fr/industries/food-and-drink/free-foods/                                                              |
     | fr/industries/food-and-drink/meat-poultry-and-dairy/                                                  |
     | fr/industries/health-and-life-sciences/                                                               |
     | fr/industries/health-and-life-sciences/medical-technology/                                            |
     | fr/industries/health-and-life-sciences/pharmaceutical-manufacturing/                                  |
     | fr/industries/retail/                                                                                 |
     | fr/industries/technology/                                                                             |
     | fr/industries/technology/data-analytics/                                                              |
     | fr/uk-regions/london/                                                                                 |
     | fr/uk-regions/midlands/                                                                               |
     | fr/uk-regions/north-england/                                                                          |
     | fr/uk-regions/northern-ireland/                                                                       |
     | fr/uk-regions/scotland/                                                                               |
     | fr/uk-regions/south-england/                                                                          |
     | fr/uk-regions/wales/                                                                                  |
     | fr/uk-setup-guide/                                                                                    |
     | fr/uk-setup-guide/apply-uk-visa/                                                                      |
     | fr/uk-setup-guide/establish-base-business-uk/                                                         |
     | fr/uk-setup-guide/hire-skilled-workers-your-uk-operations/                                            |
     | fr/uk-setup-guide/open-uk-business-bank-account/                                                      |
     | fr/uk-setup-guide/setup-your-business-uk/                                                             |
     | fr/uk-setup-guide/understand-uk-tax-and-incentives/                                                   |

    Examples: Japanese
     | selected                                                                                              |
     | ja/                                                                                                   |
     | ja/contact/                                                                                           |
     | ja/industries/                                                                                        |
     | ja/industries/advanced-manufacturing/                                                                 |
     | ja/industries/aerospace/                                                                              |
     | ja/industries/agri-tech/                                                                              |
     | ja/industries/automotive/                                                                             |
     | ja/industries/automotive/automotive-research-and-development/                                         |
     | ja/industries/automotive/automotive-supply-chain/                                                     |
     | ja/industries/automotive/motorsport/                                                                  |
     | ja/industries/chemicals/                                                                              |
     | ja/industries/creative-industries/                                                                    |
     | ja/industries/creative-industries/creative-content-and-production/                                    |
     | ja/industries/creative-industries/digital-media/                                                      |
     | ja/industries/energy/                                                                                 |
     | ja/industries/energy/electrical-networks/                                                             |
     | ja/industries/energy/energy-waste/                                                                    |
     | ja/industries/energy/nuclear-energy/                                                                  |
     | ja/industries/energy/offshore-wind-energy/                                                            |
     | ja/industries/energy/oil-and-gas/                                                                     |
     | ja/industries/financial-services/                                                                     |
     | ja/industries/financial-services/asset-management/                                                    |
     | ja/industries/financial-services/financial-technology/                                                |
     | ja/industries/food-and-drink/                                                                         |
     | ja/industries/food-and-drink/food-service-and-catering/                                               |
     | ja/industries/food-and-drink/free-foods/                                                              |
     | ja/industries/food-and-drink/meat-poultry-and-dairy/                                                  |
     | ja/industries/health-and-life-sciences/                                                               |
     | ja/industries/health-and-life-sciences/medical-technology/                                            |
     | ja/industries/health-and-life-sciences/pharmaceutical-manufacturing/                                  |
     | ja/industries/retail/                                                                                 |
     | ja/industries/technology/                                                                             |
     | ja/industries/technology/data-analytics/                                                              |
     | ja/uk-regions/london/                                                                                 |
     | ja/uk-regions/north-england/                                                                          |
     | ja/uk-regions/northern-ireland/                                                                       |
     | ja/uk-regions/scotland/                                                                               |
     | ja/uk-regions/south-england/                                                                          |
     | ja/uk-regions/wales/                                                                                  |
     | ja/uk-setup-guide/                                                                                    |
     | ja/uk-setup-guide/apply-uk-visa/                                                                      |
     | ja/uk-setup-guide/establish-base-business-uk/                                                         |
     | ja/uk-setup-guide/hire-skilled-workers-your-uk-operations/                                            |
     | ja/uk-setup-guide/open-uk-business-bank-account/                                                      |
     | ja/uk-setup-guide/setup-your-business-uk/                                                             |
     | ja/uk-setup-guide/understand-uk-tax-and-incentives/                                                   |

    Examples: Portuguese
     | selected                                                                                              |
     | pt/                                                                                                   |
     | pt/contact/                                                                                           |
     | pt/industries/                                                                                        |
     | pt/industries/advanced-manufacturing/                                                                 |
     | pt/industries/aerospace/                                                                              |
     | pt/industries/agri-tech/                                                                              |
     | pt/industries/automotive/                                                                             |
     | pt/industries/automotive/automotive-research-and-development/                                         |
     | pt/industries/automotive/automotive-supply-chain/                                                     |
     | pt/industries/automotive/motorsport/                                                                  |
     | pt/industries/capital-investment/                                                                     |
     | pt/industries/chemicals/                                                                              |
     | pt/industries/creative-industries/                                                                    |
     | pt/industries/creative-industries/creative-content-and-production/                                    |
     | pt/industries/creative-industries/digital-media/                                                      |
     | pt/industries/energy/                                                                                 |
     | pt/industries/energy/electrical-networks/                                                             |
     | pt/industries/energy/energy-waste/                                                                    |
     | pt/industries/energy/nuclear-energy/                                                                  |
     | pt/industries/energy/offshore-wind-energy/                                                            |
     | pt/industries/energy/oil-and-gas/                                                                     |
     | pt/industries/food-and-drink/                                                                         |
     | pt/industries/food-and-drink/food-service-and-catering/                                               |
     | pt/industries/food-and-drink/free-foods/                                                              |
     | pt/industries/food-and-drink/meat-poultry-and-dairy/                                                  |
     | pt/industries/health-and-life-sciences/                                                               |
     | pt/industries/health-and-life-sciences/medical-technology/                                            |
     | pt/industries/health-and-life-sciences/pharmaceutical-manufacturing/                                  |
     | pt/industries/retail/                                                                                 |
     | pt/industries/technology/                                                                             |
     | pt/industries/technology/data-analytics/                                                              |
     | pt/uk-regions/london/                                                                                 |
     | pt/uk-regions/midlands/                                                                               |
     | pt/uk-regions/north-england/                                                                          |
     | pt/uk-regions/northern-ireland/                                                                       |
     | pt/uk-regions/scotland/                                                                               |
     | pt/uk-regions/south-england/                                                                          |
     | pt/uk-regions/wales/                                                                                  |
     | pt/uk-setup-guide/                                                                                    |
     | pt/uk-setup-guide/apply-uk-visa/                                                                      |
     | pt/uk-setup-guide/establish-base-business-uk/                                                         |
     | pt/uk-setup-guide/hire-skilled-workers-your-uk-operations/                                            |
     | pt/uk-setup-guide/open-uk-business-bank-account/                                                      |
     | pt/uk-setup-guide/setup-your-business-uk/                                                             |
     | pt/uk-setup-guide/understand-uk-tax-and-incentives/                                                   |

    Examples: Chinese
     | selected                                                                                                |
     | zh-hans/                                                                                                |
     | zh-hans/contact/                                                                                        |
     | zh-hans/industries/                                                                                     |
     | zh-hans/industries/advanced-manufacturing/                                                              |
     | zh-hans/industries/aerospace/                                                                           |
     | zh-hans/industries/agri-tech/                                                                           |
     | zh-hans/industries/automotive/                                                                          |
     | zh-hans/industries/automotive/automotive-research-and-development/                                      |
     | zh-hans/industries/automotive/automotive-supply-chain/                                                  |
     | zh-hans/industries/automotive/motorsport/                                                               |
     | zh-hans/industries/chemicals/                                                                           |
     | zh-hans/industries/creative-industries/                                                                 |
     | zh-hans/industries/creative-industries/creative-content-and-production/                                 |
     | zh-hans/industries/creative-industries/digital-media/                                                   |
     | zh-hans/industries/energy/                                                                              |
     | zh-hans/industries/energy/electrical-networks/                                                          |
     | zh-hans/industries/energy/energy-waste/                                                                 |
     | zh-hans/industries/energy/nuclear-energy/                                                               |
     | zh-hans/industries/energy/offshore-wind-energy/                                                         |
     | zh-hans/industries/energy/oil-and-gas/                                                                  |
     | zh-hans/industries/financial-services/                                                                  |
     | zh-hans/industries/financial-services/asset-management/                                                 |
     | zh-hans/industries/financial-services/financial-technology/                                             |
     | zh-hans/industries/food-and-drink/                                                                      |
     | zh-hans/industries/food-and-drink/food-service-and-catering/                                            |
     | zh-hans/industries/food-and-drink/free-foods/                                                           |
     | zh-hans/industries/food-and-drink/meat-poultry-and-dairy/                                               |
     | zh-hans/industries/health-and-life-sciences/                                                            |
     | zh-hans/industries/health-and-life-sciences/medical-technology/                                         |
     | zh-hans/industries/health-and-life-sciences/pharmaceutical-manufacturing/                               |
     | zh-hans/industries/retail/                                                                              |
     | zh-hans/industries/technology/                                                                          |
     | zh-hans/industries/technology/data-analytics/                                                           |
     | zh-hans/uk-regions/london/                                                                              |
     | zh-hans/uk-regions/midlands/                                                                            |
     | zh-hans/uk-regions/north-england/                                                                       |
     | zh-hans/uk-regions/northern-ireland/                                                                    |
     | zh-hans/uk-regions/scotland/                                                                            |
     | zh-hans/uk-regions/south-england/                                                                       |
     | zh-hans/uk-regions/wales/                                                                               |
     | zh-hans/uk-setup-guide/                                                                                 |
     | zh-hans/uk-setup-guide/apply-uk-visa/                                                                   |
     | zh-hans/uk-setup-guide/establish-base-business-uk/                                                      |
     | zh-hans/uk-setup-guide/hire-skilled-workers-your-uk-operations/                                         |
     | zh-hans/uk-setup-guide/open-uk-business-bank-account/                                                   |
     | zh-hans/uk-setup-guide/setup-your-business-uk/                                                          |
     | zh-hans/uk-setup-guide/understand-uk-tax-and-incentives/                                                |

   @wip
    Examples: Pages that are hosted on a different service or are not present any longer
     | selected                                                                                              |
     | feedback/                                                                                             |
     | ar/feedback/                                                                                          |
     | de/feedback/                                                                                          |
     | es/feedback/                                                                                          |
     | fr/feedback/                                                                                          |
     | ja/feedback/                                                                                          |
     | pt/feedback/                                                                                          |
     | zh-cn/feedback/                                                                                       |
     | zh-cn/terms-and-conditions/                                                                           |
     | pt/terms-and-conditions/                                                                              |
     | ja/terms-and-conditions/                                                                              |
     | fr/terms-and-conditions/                                                                              |
     | es/terms-and-conditions/                                                                              |
     | de/terms-and-conditions/                                                                              |
     | ar/terms-and-conditions/                                                                              |
     | terms-and-conditions/                                                                                 |
     | privacy-and-cookies/                                                                                  |
     | privacy-and-cookies/fair-processing-notice-export-opportunities/                                      |
     | privacy-and-cookies/fair-processing-notice-export-readiness/                                          |
     | privacy-and-cookies/fair-processing-notice-for-smart-survey/                                          |
     | privacy-and-cookies/fair-processing-notice-invest-in-great-britain/                                   |
     | privacy-and-cookies/fair-processing-notice-selling-online-overseas/                                   |
     | privacy-and-cookies/fair-processing-notice-trade-profiles-find-a-buyer-fab-find-a-supplier-fas/       |
     | privacy-and-cookies/fair-processing-notice-zendesk/                                                   |
     | ar/privacy-and-cookies/                                                                               |
     | ar/privacy-and-cookies/fair-processing-notice-export-opportunities/                                   |
     | ar/privacy-and-cookies/fair-processing-notice-export-readiness/                                       |
     | ar/privacy-and-cookies/fair-processing-notice-for-smart-survey/                                       |
     | ar/privacy-and-cookies/fair-processing-notice-invest-in-great-britain/                                |
     | ar/privacy-and-cookies/fair-processing-notice-selling-online-overseas/                                |
     | ar/privacy-and-cookies/fair-processing-notice-trade-profiles-find-a-buyer-fab-find-a-supplier-fas/    |
     | ar/privacy-and-cookies/fair-processing-notice-zendesk/                                                |
     | de/privacy-and-cookies/                                                                               |
     | de/privacy-and-cookies/fair-processing-notice-export-opportunities/                                   |
     | de/privacy-and-cookies/fair-processing-notice-export-readiness/                                       |
     | de/privacy-and-cookies/fair-processing-notice-for-smart-survey/                                       |
     | de/privacy-and-cookies/fair-processing-notice-invest-in-great-britain/                                |
     | de/privacy-and-cookies/fair-processing-notice-selling-online-overseas/                                |
     | de/privacy-and-cookies/fair-processing-notice-trade-profiles-find-a-buyer-fab-find-a-supplier-fas/    |
     | de/privacy-and-cookies/fair-processing-notice-zendesk/                                                |
     | es/privacy-and-cookies/                                                                               |
     | es/privacy-and-cookies/fair-processing-notice-export-opportunities/                                   |
     | es/privacy-and-cookies/fair-processing-notice-export-readiness/                                       |
     | es/privacy-and-cookies/fair-processing-notice-for-smart-survey/                                       |
     | es/privacy-and-cookies/fair-processing-notice-invest-in-great-britain/                                |
     | es/privacy-and-cookies/fair-processing-notice-selling-online-overseas/                                |
     | es/privacy-and-cookies/fair-processing-notice-trade-profiles-find-a-buyer-fab-find-a-supplier-fas/    |
     | es/privacy-and-cookies/fair-processing-notice-zendesk/                                                |
     | fr/privacy-and-cookies/                                                                               |
     | fr/privacy-and-cookies/fair-processing-notice-export-opportunities/                                   |
     | fr/privacy-and-cookies/fair-processing-notice-export-readiness/                                       |
     | fr/privacy-and-cookies/fair-processing-notice-for-smart-survey/                                       |
     | fr/privacy-and-cookies/fair-processing-notice-invest-in-great-britain/                                |
     | fr/privacy-and-cookies/fair-processing-notice-selling-online-overseas/                                |
     | fr/privacy-and-cookies/fair-processing-notice-trade-profiles-find-a-buyer-fab-find-a-supplier-fas/    |
     | fr/privacy-and-cookies/fair-processing-notice-zendesk/                                                |
     | ja/privacy-and-cookies/                                                                               |
     | ja/privacy-and-cookies/fair-processing-notice-export-opportunities/                                   |
     | ja/privacy-and-cookies/fair-processing-notice-export-readiness/                                       |
     | ja/privacy-and-cookies/fair-processing-notice-for-smart-survey/                                       |
     | ja/privacy-and-cookies/fair-processing-notice-invest-in-great-britain/                                |
     | ja/privacy-and-cookies/fair-processing-notice-selling-online-overseas/                                |
     | ja/privacy-and-cookies/fair-processing-notice-trade-profiles-find-a-buyer-fab-find-a-supplier-fas/    |
     | ja/privacy-and-cookies/fair-processing-notice-zendesk/                                                |
     | pt/privacy-and-cookies/                                                                               |
     | pt/privacy-and-cookies/fair-processing-notice-export-opportunities/                                   |
     | pt/privacy-and-cookies/fair-processing-notice-export-readiness/                                       |
     | pt/privacy-and-cookies/fair-processing-notice-for-smart-survey/                                       |
     | pt/privacy-and-cookies/fair-processing-notice-invest-in-great-britain/                                |
     | pt/privacy-and-cookies/fair-processing-notice-selling-online-overseas/                                |
     | pt/privacy-and-cookies/fair-processing-notice-trade-profiles-find-a-buyer-fab-find-a-supplier-fas/    |
     | pt/privacy-and-cookies/fair-processing-notice-zendesk/                                                |
     | zh-cn/privacy-and-cookies/                                                                            |
     | zh-cn/privacy-and-cookies/fair-processing-notice-export-opportunities/                                |
     | zh-cn/privacy-and-cookies/fair-processing-notice-export-readiness/                                    |
     | zh-cn/privacy-and-cookies/fair-processing-notice-for-smart-survey/                                    |
     | zh-cn/privacy-and-cookies/fair-processing-notice-invest-in-great-britain/                             |
     | zh-cn/privacy-and-cookies/fair-processing-notice-selling-online-overseas/                             |
     | zh-cn/privacy-and-cookies/fair-processing-notice-trade-profiles-find-a-buyer-fab-find-a-supplier-fas/ |
     | zh-cn/privacy-and-cookies/fair-processing-notice-zendesk/                                             |
